scrape_configs:
- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - targets:
    - prometheus:9090
- job_name: blackbox
  metrics_path: /probe
  scrape_interval: 5s
  params:
    module: [http_2xx] 
  static_configs:
  - targets:
    - http://host.docker.internal:2607/healthcheck
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox:9115
- job_name: "Metrics-from-blazor"
  scrape_interval: 5s
  static_configs:
    - target: ["luris_server"]
- job_name: Prometheus
  scrape_interval: 5s
  static_config:
    - targets:
      - prometheus:9090
