name: Garion Runner
on: [push]
#wd: /home/garion/actions-runner/_work/ticketsrus-garion-luris/ticketsrus-garion-luris
jobs:
  Deploy:
    runs-on: garion-ticket-runner
    steps:
      - name: "Docker Down"
        run: cd garion-staging && docker compose down -v 
      - name: "Clone repo"
        run: cd ../ && rm -rf ticketsrus-garion-luris || true && git clone https://${{ secrets.GARION_CLONE_KEY }}@github.com/SnowSE/ticketsrus-garion-luris.git
      - name: "Run docker compose"
        run: cd garion-staging && docker compose up --build -d
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
            webhook_url: ${{ secrets.GARION_WEBHOOK }}
            needs: ${{ toJson(needs) }}
            job: ${{ toJson(job) }}
            steps: ${{ toJson(steps) }}
            dry_run: True