name: CI_LurisRunner
on: [push]
jobs:
  deploypipeline:
    runs-on: labelTicket
    steps:
      - name: "do something to remove"
        run: |
          rm -rf ./TelemetryTickets
      - name: "Clonning the repo"
        run: git clone https://${{secrets.CI_LURIS}}@github.com/luris26/TelemetryTickets.git

      - name: Test
        run: |
          cd ./TicketsRUs.Tests/
          dotnet test
      - name: "Run docker compose"
        run: |
          cd ./TelemetryTickets/LurisDockercompose
          docker compose up --build -d



#Do something
################################################Im Done#############################################################################


