name: LurisRunner
on: [push]
jobs:
  deploypipeline:
    runs-on: labelTicket
    steps:
      - name: "do something to remove"
        run: |
          rm -rf ./ticketsrus-garion-luris
      - name: "Clonning the repo"
        run: git clone https://${{secrets.CI_LURIS}}@github.com/SnowSE/ticketsrus-garion-luris.git
      - name: "Run docker compose"
        run: |
          cd ./ticketsrus-garion-luris/LurisDockercompose
          docker compose up --build -d
#Do something
################################################Im Done#############################################################################


