name: CI_LurisRunner
on: [push]
jobs:
  deploypipeline:
    runs-on: labelTicket
    steps:
      - name: "do something to remove"
        run: |
          rm -rf ./TelemetryTickets
      - name: "Clonning the repo"
        run: git clone https://${{secrets.CI_LURIS}}@github.com/luris26/TelemetryTickets.git

      - name: Test
        run: | 
          cd ./TelemetryTickets/TicketsRUs.Tests   
          dotnet test       

      # - name: Linting
      #   run: |
      #     cd ./TelemetryTickets/TicketsRUs.Tests 
      #     dotnet format --verify-no-changes --severity warn

      # - name: Warning Errors
      #   run: |
      #     cd ./TelemetryTickets/TicketsRUs.Tests

      # - name: "Run docker compose"
      #   run: |
      #     cd ./TelemetryTickets/LurisDockercompose
      #     docker compose up --build -d
##
      


#Do something
################################################Im Done#############################################################################


