name: CI_LurisRunner
on: [push]
jobs:
  deploypipeline:
    runs-on: labelTicket
    steps:
      - name: "do something to remove"
        run: |
          rm -rf ./TelemetryTickets
      - name: "Clonning the repo"
        run: git clone https://${{secrets.CI_LURIS}}@github.com/luris26/TelemetryTickets.git
      # - name: Test Unit
      #   run: | 
      #     # docker run --rm --network="container:dbcontainer" -v "$(pwd):/app" -w /app/elemetryTickets -e DOTNET_CLI_HOME="/tmp/dotnet" --user $(id -u):$(id -g) mcr.microsoft.com/dotnet/sdk:8.0 dotnet test
      #     cd ./TelemetryTickets/TicketsRUs.Tests   
      #     dotnet test 
      # - name: Test Integration Test
      #   run: | 
      #     cd ./TelemetryTickets/TicketsRus.IntegrationTest  
      #     dotnet test       
      
      - name: Linting
        run: |
          cd ./TelemetryTickets/TicketsRUs.Tests 
          dotnet format --verify-no-changes --severity warn
      - name: "Turn On Containers"
        run: |
          cd ./TelemetryTickets/LurisDockercompose
          docker compose up --build -d
##
  # run-on-github-actions:
  #   runs-on: [ labelTicket ]
  #   needs: [ deploypipeline]
  #   steps:
  #     - name: "Turn On Containers"
  #       run: |
  #         cd ./TelemetryTickets/LurisDockercompose
  #         docker compose up --build -d








