name: CI_LurisRunner
on: [push]
jobs:
  deploypipeline:
    runs-on: labelTicket
    steps:
      - name: "do something to remove"
        run: |
          rm -rf ./TelemetryTickets
      - name: "Clonning the repo"
        run: git clone https://${{secrets.CI_LURIS}}@github.com/luris26/TelemetryTickets.git

      - name: Test
        run: | 
          cd ./TelemetryTickets/TicketsRUs.Tests          
          docker run --rm -v "$(pwd):/app" -w /app/TicketsRUs.Tests -e DOTNET_CLI_HOME="/tmp/dotnet" --user $(id -u):$(id -g) mcr.microsoft.com/dotnet/sdk:8.0 dotnet test

      # - name: Linting
      #   run: 

      - name: "Run docker compose"
        run: |
          cd ./TelemetryTickets/LurisDockercompose
          docker compose up --build -d
##
      


#Do something
################################################Im Done#############################################################################


