name: CI_LurisRunner
on: [push]
jobs:
  deploypipeline:
    runs-on: labelTicket
    steps:
      - uses: actions/checkout@v4
      
      - name: "do something to remove"
        run: |
          rm -rf ./TelemetryTickets
      - name: "Clonning the repo"
        run: git clone https://${{secrets.CI_LURIS}}@github.com/luris26/TelemetryTickets.git
      # - name: Test Unit
      #   run: | 
      #     # docker run --rm --network="container:dbcontainer" -v "$(pwd):/app" -w /app/elemetryTickets -e DOTNET_CLI_HOME="/tmp/dotnet" --user $(id -u):$(id -g) mcr.microsoft.com/dotnet/sdk:8.0 dotnet test
      #     cd ./TelemetryTickets/TicketsRUs.Tests   
      #     dotnet test 
      # - name: Test Integration Test
      #   run: | 
      #     cd ./TelemetryTickets/TicketsRus.IntegrationTest  
      #     dotnet test       
      
      - name: Linting
        run: |
          cd ./TelemetryTickets/TicketsRUs.Tests 
          dotnet format --verify-no-changes --severity warn
      - name: "Turn On Containers"
        run: |
          cd ./TelemetryTickets/LurisDockercompose
          docker compose up --build -d

      - name: deploy
        run: |
          cd ./TelemetryTickets/LurisDockercompose
          docker compose down 
          docker compose up --build -d

      - name: deploy-kube
        run: |
          cd ./TelemetryTickets
          docker build -t 144.17.92.12:5000/luris/blazor-web:1 .
          docker push 144.17.92.12:5000/luris/blazor-web:1 

          # kubectl -n luris create configmap blazor-web-postgres-init --from-file=init.sql
          cd kube-configs
          # kubectl -n luris delete configmap otel-collector-config || true
          # kubectl -n luris create configmap otel-collector-config --from-file=init.sql
          kubectl -n luris delete configmap grafana-datasource-config || true
          kubectl -n luris create configmap grafana-datasource-config --from-file=datasource-deployment.yml
          cd ..
          kubectl apply -f Kube/
##################################################################################################








